// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CalculateTotalPrice(ctx context.Context, arg CalculateTotalPriceParams) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteSubscription(ctx context.Context, id uuid.UUID) error
	GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error)
	ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
