// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateTotalPrice = `-- name: CalculateTotalPrice :one
SELECT COALESCE(SUM(
    price * (
        EXTRACT(YEAR FROM age(
            LEAST(COALESCE(end_date, $1::date), $1::date),
            GREATEST(start_date, $2::date)
        ))::int * 12
        + EXTRACT(MONTH FROM age(
            LEAST(COALESCE(end_date, $1::date), $1::date),
            GREATEST(start_date, $2::date)
        ))::int
        + 1
    )
), 0)::bigint AS total_price
FROM subscriptions
WHERE start_date <= $1::date
  AND COALESCE(end_date, $1::date) >= $2::date
  AND ($3::uuid IS NULL OR user_id = $3::uuid)
  AND ($4::text IS NULL OR service_name = $4::text)
`

type CalculateTotalPriceParams struct {
	PeriodTo          pgtype.Date `json:"period_to"`
	PeriodFrom        pgtype.Date `json:"period_from"`
	UserIDFilter      pgtype.UUID `json:"user_id_filter"`
	ServiceNameFilter pgtype.Text `json:"service_name_filter"`
}

func (q *Queries) CalculateTotalPrice(ctx context.Context, arg CalculateTotalPriceParams) (int64, error) {
	row := q.db.QueryRow(ctx, calculateTotalPrice,
		arg.PeriodTo,
		arg.PeriodFrom,
		arg.UserIDFilter,
		arg.ServiceNameFilter,
	)
	var total_price int64
	err := row.Scan(&total_price)
	return total_price, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    service_name,
    price,
    user_id,
    start_date,
    end_date
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      uuid.UUID   `json:"user_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::text IS NULL OR service_name = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
OFFSET $3::int
`

type ListSubscriptionsParams struct {
	UserIDFilter      pgtype.UUID `json:"user_id_filter"`
	ServiceNameFilter pgtype.Text `json:"service_name_filter"`
	OffsetValue       int32       `json:"offset_value"`
	LimitValue        int32       `json:"limit_value"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserIDFilter,
		arg.ServiceNameFilter,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET service_name = $2,
    price = $3,
    user_id = $4,
    start_date = $5,
    end_date = $6
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          uuid.UUID   `json:"id"`
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      uuid.UUID   `json:"user_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
